const tracks = [
    // Existing tracks...
    {
      title: "Who's Driving",
      album: "Snow",
      date: "2024-01-18",
      time: "03:45",
      img: "https://img.mensxp.com/media/content/2020/Apr/Leading-B-Wood-Singers-Who-Lost-On-Reality-Shows1200_5ea7d3e1ba5f2.jpeg",
      music: "./music1.mp3",
    },
    {
      title: "Kiliye",
      album: "Chithrum",
      date: "2024-01-19",
      time: "04:30",
      img: "https://images.indulgexpress.com/uploads/user/imagelibrary/2023/6/29/original/InFrameKSChithra.jpg",
      music: "./music2.mp3",
    },
    {
      title: "Balcony",
      album: "Balcony",
      date: "2024-01-19",
      time: "04:30",
      img: "https://images.saymedia-content.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:eco%2Cw_1200/MTg2MTA4Njk5MDQxODY2ODgx/top-5-hottest-young-singers-today.jpg",
      music: "./music3.mp3",
    },
    {
      title: "Snake",
      album: "Taylor Snake",
      date: "2024-01-19",
      time: "04:30",
      img: "https://samacharlagatar.com/wp-content/uploads/2023/09/5-hollywood-singers-who-became-acclaimed-actors-1.jpg",
      music: "./music4.mp3",
    },
    {
      title: "Glow",
      album: "glow",
      date: "2024-01-19",
      time: "04:30",
      img: "https://e0.pxfuel.com/wallpapers/76/35/desktop-wallpaper-zoya-blodos-world-s-famous-singers-american-hot-and-actress-thumbnail.jpg",
      music: "./music1.mp3",
    },
    {
      title: "Daffy",
      album: "Summer",
      date: "2024-01-19",
      time: "04:30",
      img: "https://www.musicianwave.com/wp-content/uploads/2022/04/Zayn-Malik-393x525.jpg",
      music: "./music1.mp3",
    },
    // Additional tracks...
    {
      title: "Moonlight Sonata",
      album: "Classical Classics",
      date: "2024-01-20",
      time: "05:15",
      img: "https://fancyodds.com/wp-content/uploads/2021/08/Nicki-Minaj.jpg",
      music: "./music4.mp3",
    },
    {
      title: "City Lights",
      album: "Urban Vibes",
      date: "2024-01-21",
      time: "03:55",
      img: "https://www.superprof.co.in/blog/wp-content/uploads/2023/03/image2-4.png",
      music: "./music1.mp3",
    },
    {
      title: "Summer Breeze",
      album: "Seasonal Sounds",
      date: "2024-01-22",
      time: "04:10",
      img: "https://hi.letsdiskuss.com/assets/upl_files/bdeb8e0ead.jpg",
      music: "./music3.mp3",
    },
    {
      title: "Eclipse",
      album: "Galactic Grooves",
      date: "2024-01-23",
      time: "04:45",
      img: "https://theindianeye.com/wp-content/uploads/2022/10/Shreya-1.jpg",
      music: "./music4.mp3",
    },
    {
      title: "Jazzed Up",
      album: "Smooth Jazz",
      date: "2024-01-24",
      time: "03:30",
      img: "https://d18hry5vavz86j.cloudfront.net/BlogImages/dedbdba9-412a-4d4f-92a9-d36b529b7948.jpg",
      music: "./music3.mp3",
    },
    {
      title: "Rising Sun",
      album: "Morning Melodies",
      date: "2024-01-25",
      time: "04:20",
      img: "https://img.mensxp.com/media/content/2020/Apr/Leading-B-Wood-Singers-Who-Lost-On-Reality-Shows1200_5ea7d3e1ba5f2.jpeg",
      music: "./music1.mp3",
    },
  ];
  
  export default tracks;
  